sudo: required
services:
  - docker

before_install:
  - docker build -t coniix/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true coniix/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucked_name: "elasticbeanstalk-eu-north-1-313582925907"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"